queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Run Integration Tests
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - status-success=Analyze (javascript)

pull_request_rules:
  - name: Automatically merge on CI success and review approval
    conditions:
      - base~=master|integ-tests
      - "#approved-reviews-by>=1"
      - approved-reviews-by=@aws-actions/aws-ecs-devx
      - -approved-reviews-by~=author
      - status-success=Run Integration Tests
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - status-success=Analyze (javascript)
      - label!=work-in-progress
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - author!=dependabot[bot]
    actions:
      queue:
        method: squash
        name: default

  - name: Automatically approve Dependabot PRs
    conditions:
      - base=master
      - author=dependabot[bot]
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - status-success=Analyze (javascript)
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE

    - name: Automatically merge Dependabot PRs
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - author=dependabot[bot]
      - status-success=Run Integration Tests
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - status-success=Analyze (javascript)
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      queue:
        method: squash
        name: default