on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: BUILD_ID

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy Amazon ECS task definition With Wait For Task Stopped Being False
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition-run-task.json
        cluster: ${{ env.ECS_CLUSTER }}
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-assign-public-IP: ENABLED
        run-task-security-groups: sg-067ebcde49c0f3ad8, sg-148d093a
        run-task-launch-type: FARGATE
        wait-for-task-stopped: false 

    - name: Deploy Amazon ECS task definition With Wait For Task Stopped Being True
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition-run-task.json
        cluster: ${{ env.ECS_CLUSTER }}
        run-task: true
        run-task-subnets: subnet-e5604fce, subnet-fe9355b4, subnet-c49431bc, subnet-392f9b64
        run-task-assign-public-IP: ENABLED
        run-task-security-groups: sg-067ebcde49c0f3ad8, sg-148d093a
        run-task-launch-type: FARGATE
        wait-for-task-stopped: true

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
