name: Approval Workflow

on:
    workflow_dispatch:
    # pull_request_review:
    #   types: [submitted]
jobs:
    approved:
        # if: github.event.review.state == 'approved'
        runs-on: ubuntu-latest
        steps:
            - name: Run Integration Tests
              run: |
                echo ${{ github.head_ref }}